---
- name: prepare container for test
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create container centos7
      docker_container:
        name: centos7
        image: centos:7
        recreate: yes
        command: tail -f /dev/null
        state: started

    - name: Create container fedora25
      docker_container:
        name: fedora25
        image: fedora:25
        recreate: yes
        command: tail -f /dev/null
        state: started


    - name: Install python to fedora
      command: "docker exec fedora25 dnf install -y python python2-dnf"

    - name: add hosts
      add_host:
        name: '{{ item }}'
        groups: containers
      with_items:
        - fedora25
        - centos7

- name: test role
  hosts: containers
  connection: docker
  roles:
    - role: "{{ playbook_dir }}"

- name: tear down
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Destroy containers
      docker_container:
        name: '{{ item }}'
        state: absent
      with_items:
        - fedora25
        - centos7
