---
- name: Include platform specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Install common packages
  package:
    name: "{{ _bootstrap_common_pkg }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install distribution specific packages
  package:
    name: "{{ _bootstrap_distribution_specific_pkg }}"
    state: present
  when: _bootstrap_distribution_specific_pkg is defined

- name: Add ssh agent line to sudoers.d/auth_socket
  copy:
    content: |
      Defaults env_keep += "SSH_AUTH_SOCK"
    dest: '/etc/sudoers.d/auth_socket'
    mode: '0644'

- name: Remove ssh agent line from sudoers
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep += "SSH_AUTH_SOCK"
    validate: 'visudo -cf %s'
